// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplesSaborMVC.Data;

#nullable disable

namespace SimplesSaborMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106135735_criarbanco")]
    partial class criarbanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ExibirHome")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExibirHome = true,
                            Foto = "/img/categorias/1.jpg",
                            Nome = "Café da Manhã"
                        },
                        new
                        {
                            Id = 2,
                            ExibirHome = false,
                            Foto = "/img/categorias/2.jpg",
                            Nome = "Almoço"
                        },
                        new
                        {
                            Id = 3,
                            ExibirHome = true,
                            Foto = "/img/categorias/3.jpg",
                            Nome = "Jantar "
                        },
                        new
                        {
                            Id = 4,
                            ExibirHome = true,
                            Foto = "/img/categorias/1.jpg",
                            Nome = "Bebidas"
                        });
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ovo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Brócolis"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Sal"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Queijo "
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Azeite"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Batata "
                        },
                        new
                        {
                            Id = 7,
                            Nome = "rabanete"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Tomate "
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Orégano "
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Aveia"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Linhaça "
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Coco em Flocos"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Açúcar Mascavo "
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Cacau em Pó"
                        },
                        new
                        {
                            Id = 15,
                            Nome = " Leite Desnatado "
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Morangos "
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Amêndoas"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Cacau "
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Água "
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Espinafre"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Frutas Vermelhas "
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Iogurte"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Whey"
                        },
                        new
                        {
                            Id = 24,
                            Nome = " Castanhas"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Pão "
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Abacate "
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Manteiga"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Chia "
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Pimenta  "
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Banana"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Canela "
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Baunilha "
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Requeijão "
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Carne"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Arroz"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Cebola "
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Frango"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Batata Doce"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Salmão"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Limão"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "macarrão"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Alho"
                        },
                        new
                        {
                            Id = 43,
                            Nome = "Molho de Tomate"
                        },
                        new
                        {
                            Id = 44,
                            Nome = "Pimentões"
                        },
                        new
                        {
                            Id = 45,
                            Nome = "Cenoura"
                        },
                        new
                        {
                            Id = 46,
                            Nome = "Salada"
                        },
                        new
                        {
                            Id = 47,
                            Nome = "salsinha"
                        },
                        new
                        {
                            Id = 48,
                            Nome = "Laranja"
                        },
                        new
                        {
                            Id = 49,
                            Nome = "Mel"
                        },
                        new
                        {
                            Id = 50,
                            Nome = "Panqueca"
                        },
                        new
                        {
                            Id = 51,
                            Nome = "Berinjela"
                        });
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Preparo")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("Rendimento")
                        .HasColumnType("int");

                    b.Property<string>("TempoPreparo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Receita");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorias = 282,
                            CategoriaId = 1,
                            Descricao = "Prato perfeito para um lanche rápido ou mesmo uma refeição picante. Carne moída, pimentões, temperos e muito queijooooo",
                            Foto = "/assets/images/dish/omelete_de_legumes.png",
                            Nome = "Omelete de Legumes",
                            Preparo = "Comece pela preparação dos ingredientes, pique os pimentões e a cebola em pequenos cubos, se preferir você também pode usar um processador de alimentos.Coloque a carne moída para fritar em uma panela com um pouco de azeite.Quando a carne moída já não estiver mais crua, adicione os pimentões e a cebola, mexendo bem para misturar todos os ingredientes.Aguarde alguns instante e adicione os temperos, mexendo novamente para misturar.Frite por mais alguns minutos a carne com os demais ingredientes.Adicione o Cream Cheese e o Queijo Cheddar, mexendo bem para evitar que queime o fundo e ajudar os queijos a derreterem.Quando os queijos já estiverem bem derretidos e misturados com os demais ingredientes, sirva acompanhado do Pão Sirio ou de Doritos.",
                            Rendimento = 1,
                            TempoPreparo = "15 minutos",
                            Tipo = "Ganho de Massa"
                        },
                        new
                        {
                            Id = 2,
                            Calorias = 127,
                            CategoriaId = 1,
                            Foto = "/assets/images/dish/aveia_com_frutas.png",
                            Nome = "Aveia com Frutas",
                            Preparo = "Em uma tigela, misture a aveia, a linhaça, o coco em flocos, o açúcar mascavo, o cacau em pó e o leite. Reserve na geladeira de um dia para o outro. No momento de servir, coloque uma porção em uma tigela e finalize com os morangos picados, a amêndoa laminada e os nibs de cacau.",
                            Rendimento = 1,
                            TempoPreparo = "10 minutos"
                        },
                        new
                        {
                            Id = 3,
                            Calorias = 162,
                            CategoriaId = 4,
                            Foto = "/assets/images/dish/smoothie_de_proteina.png",
                            Nome = "Smoothie de Proteína",
                            Preparo = "Coloque todos os ingredientes no liquidificador e bata até obter uma mistura homogênea.Sirva em um copo grande.",
                            Rendimento = 1,
                            TempoPreparo = "5 minutos"
                        },
                        new
                        {
                            Id = 4,
                            Calorias = 310,
                            CategoriaId = 1,
                            Foto = "/assets/images/dish/torrada_de_abacate.png",
                            Nome = "Torrada de Abacate",
                            Preparo = "Coloque a manteiga em uma frigideira antiaderente. Quando derreter, quebre os dois ovos, adicione uma pitada de sal e mexa até cozinhar. Reserve. Pique metade do avocado e amasse-o em uma tigela pequena. Adicione ½ limão taiti espremido, sal, pimenta e chia (opcional). Misture bem e reserve. Coloque as duas fatias de pão 7 grãos na torradeira e toste até ficarem crocantes. Para servir, espalhe o avocado no pão torrado e, em seguida, adicione os ovos mexidos. Tempere com pimenta preta e sal a gosto, ajustando conforme seu paladar. Sirva em seguida.",
                            Rendimento = 1,
                            TempoPreparo = "15 minutos"
                        },
                        new
                        {
                            Id = 5,
                            Calorias = 250,
                            CategoriaId = 1,
                            Foto = "/assets/images/dish/panquecas_de_banana.png",
                            Nome = "Panquecas de Banana",
                            Preparo = "Amasse as bananas em uma travessa funda. Adicione os ovos inteiros e misture bem. Acrescente a baunilha, a aveia e a canela (ou o chocolate em pó ou a manteiga de amendoim). Unte uma frigideira com um pouco de óleo e leve ao fogo até aquecer. Coloque uma colherada grande (ou uma concha) da massa na frigideira. Cozinhe por 2 a 3 minutos. Quando a massa começar a soltar bolhinhas, vire e deixe cozinhar por mais 1 a 2 minutos. Repita o processo de cozimento para as demais porções.",
                            Rendimento = 1,
                            TempoPreparo = "20 minutos"
                        },
                        new
                        {
                            Id = 6,
                            Calorias = 210,
                            CategoriaId = 1,
                            Foto = "/assets/images/dish/pao_com_ovos_mexidos.png",
                            Nome = "Pão com Ovos Mexidos",
                            Preparo = "Em uma tigela, coloque os ovos e bata com um garfo até obter uma mistura homogênea. Reserve. Em uma frigideira grande, aqueça a manteiga em fogo alto e adicione o ovo batido. Cozinhe, mexendo sem parar, por 3 minutos ou até mudar de consistência e estar totalmente cozido. Retire do fogo, acrescente o requeijão e misture bem. Disponha sobre as fatias de pão e sirva logo em seguida.",
                            Rendimento = 1,
                            TempoPreparo = "10 minutos"
                        },
                        new
                        {
                            Id = 7,
                            Calorias = 350,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/carne_bovina_com_arroz_integral.png",
                            Nome = "Carne Bovina com Arroz Integral",
                            Preparo = "Cozinhe o arroz integral conforme as instruções da embalagem.Enquanto isso, aqueça o azeite em uma frigideira e refogue a cebola e o alho até ficarem macios.Adicione a carne picada e cozinhe até dourar.Tempere com sal e pimenta e sirva com o arroz.",
                            Rendimento = 1,
                            TempoPreparo = "30 minutos"
                        },
                        new
                        {
                            Id = 8,
                            Calorias = 224,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/frango_grelhado_com_batata_doce.png",
                            Nome = "Frango Grelhado com Batata Doce",
                            Preparo = "Tempere o peito de frango com sal, pimenta e ervas finas.Grelhe o frango até estar bem cozido.Cozinhe a batata doce até ficar macia e depois corte em rodelas.Aqueça o azeite em uma frigideira e doure as rodelas de batata doce.",
                            Rendimento = 1,
                            TempoPreparo = "25 minutos"
                        },
                        new
                        {
                            Id = 9,
                            Calorias = 200,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/salmão_assado.png",
                            Nome = "Salmão Assado",
                            Preparo = "Tempere o salmão com azeite, suco de limão, sal, pimenta e ervas frescas.Asse em forno pré-aquecido a 180°C por cerca de 15 minutos ou até o salmão estar completamente cozido.",
                            Rendimento = 1,
                            TempoPreparo = "20 minutos"
                        },
                        new
                        {
                            Id = 10,
                            Calorias = 219,
                            CategoriaId = 3,
                            Foto = "/assets/images/dish/macarrao_integral_com_frango_desfiado.png",
                            Nome = "Macarrão Integral com Frango Desfiado",
                            Preparo = "Cozinhe o macarrão integral conforme as instruções da embalagem.Em uma panela, aqueça o azeite e refogue a cebola e o alho até ficarem macios. Adicione o frango desfiado e o molho de tomate. Cozinhe por alguns minutos até que tudo esteja bem misturado e aquecido. Misture o macarrão cozido com o frango e decore com salsinha.",
                            Rendimento = 2,
                            TempoPreparo = "25 minutos"
                        },
                        new
                        {
                            Id = 11,
                            Calorias = 153,
                            CategoriaId = 3,
                            Foto = "/assets/images/dish/iscas_de_frango_com_legumes.png",
                            Nome = "Iscas de Frango com Legumes",
                            Preparo = "Aqueça o azeite em uma frigideira e refogue as iscas de frango até dourar.Adicione os pimentões e a cenoura e continue refogando até os legumes estarem macios. Tempere com molho de soja, sal e pimenta a gosto.",
                            Rendimento = 2,
                            TempoPreparo = "20 minutos"
                        },
                        new
                        {
                            Id = 12,
                            Calorias = 70,
                            CategoriaId = 3,
                            Foto = "/assets/images/dish/isalada_colorida_de_legumes.png",
                            Nome = "Salada Colorida de Legumes",
                            Preparo = "Misture todos os legumes em uma tigela. Em uma pequena tigela separada, combine o azeite, suco de limão, sal e pimenta. Regue a salada com o molho e misture bem. Decore com salsinha antes de servir.",
                            Rendimento = 2,
                            TempoPreparo = "10 minutos"
                        },
                        new
                        {
                            Id = 13,
                            Calorias = 139,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/frango_ao_molho_de_laranja.png",
                            Nome = "Frango ao Molho de Laranja",
                            Preparo = "Tempere o frango com sal e pimenta e cozinhe em uma frigideira com um pouco de óleo até que esteja dourado e cozido por completo.Em uma panela pequena, misture o suco de laranja, molho de soja, mel e alho. Cozinhe em fogo baixo até que o molho reduza e engrosse. Sirva o frango com o molho por cima.",
                            Rendimento = 2,
                            TempoPreparo = "20 minutos"
                        },
                        new
                        {
                            Id = 14,
                            Calorias = 45,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/panqueca_integral.png",
                            Nome = "Panqueca Integral",
                            Preparo = "Misture todos os ingredientes até formar uma massa homogênea.Aqueça uma frigideira antiaderente e despeje a massa formando pequenas panquecas.Cozinhe por 2-3 minutos de cada lado, ou até que estejam douradas.",
                            Rendimento = 2,
                            TempoPreparo = "10 minutos"
                        },
                        new
                        {
                            Id = 15,
                            Calorias = 60,
                            CategoriaId = 2,
                            Foto = "/assets/images/dish/berinjela_no_forno.png",
                            Nome = "Berinjela no Forno",
                            Preparo = "Preaqueça o forno a 200°C. Coloque as rodelas de berinjela em uma assadeira e regue com azeite.Tempere com orégano, alho em pó, sal e pimenta.Asse por 20-25 minutos, virando as rodelas na metade do tempo, até que estejam macias e levemente douradas.",
                            Rendimento = 2,
                            TempoPreparo = "30 minutos"
                        });
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.ReceitaIngrediente", b =>
                {
                    b.Property<int>("ReceitaId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ReceitaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ReceitaIngrediente");

                    b.HasData(
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 1,
                            Quantidade = "3 unidades"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 2,
                            Quantidade = "5 unidade"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 4,
                            Quantidade = "1 colher"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 5,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 6,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 7,
                            Quantidade = "4 unidades"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 8,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 1,
                            IngredienteId = 9,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 10,
                            Quantidade = "1 xícara"
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 11,
                            Quantidade = "¼ xícara"
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 12,
                            Quantidade = "2 colheres "
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 13,
                            Quantidade = "1 colher de sopa "
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 14,
                            Quantidade = "2 colheres de chá"
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 15,
                            Quantidade = "1 ¼ xícara "
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 16,
                            Quantidade = "½ xícara "
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 17,
                            Quantidade = "2 colheres de sopa"
                        },
                        new
                        {
                            ReceitaId = 2,
                            IngredienteId = 18,
                            Quantidade = "1 colher de sopa "
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 19,
                            Quantidade = "350 ml "
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 20,
                            Quantidade = "1 xícara"
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 21,
                            Quantidade = "2 xícaras "
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 22,
                            Quantidade = "½ xícara "
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 23,
                            Quantidade = "2 doses"
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 24,
                            Quantidade = "1 colher de sopa "
                        },
                        new
                        {
                            ReceitaId = 3,
                            IngredienteId = 11,
                            Quantidade = "1 colher de sopa "
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 25,
                            Quantidade = "2 fatias "
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 26,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 27,
                            Quantidade = "2 colheres de chá "
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 1,
                            Quantidade = "4 unidades"
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 29,
                            Quantidade = "1 colher de chá"
                        },
                        new
                        {
                            ReceitaId = 4,
                            IngredienteId = 3,
                            Quantidade = "a gosto "
                        },
                        new
                        {
                            ReceitaId = 5,
                            IngredienteId = 30,
                            Quantidade = "2 unidades "
                        },
                        new
                        {
                            ReceitaId = 5,
                            IngredienteId = 10,
                            Quantidade = "½ xícara "
                        },
                        new
                        {
                            ReceitaId = 5,
                            IngredienteId = 31,
                            Quantidade = "1 colher de sopa"
                        },
                        new
                        {
                            ReceitaId = 5,
                            IngredienteId = 1,
                            Quantidade = "2 unidade "
                        },
                        new
                        {
                            ReceitaId = 5,
                            IngredienteId = 32,
                            Quantidade = "1 colher de sopa"
                        },
                        new
                        {
                            ReceitaId = 6,
                            IngredienteId = 1,
                            Quantidade = "5 unidade "
                        },
                        new
                        {
                            ReceitaId = 6,
                            IngredienteId = 27,
                            Quantidade = "1 colher de sopa"
                        },
                        new
                        {
                            ReceitaId = 6,
                            IngredienteId = 33,
                            Quantidade = "3 colheres de sopa  "
                        },
                        new
                        {
                            ReceitaId = 6,
                            IngredienteId = 25,
                            Quantidade = "5 fatias "
                        },
                        new
                        {
                            ReceitaId = 7,
                            IngredienteId = 34,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 7,
                            IngredienteId = 35,
                            Quantidade = "1 xicara"
                        },
                        new
                        {
                            ReceitaId = 7,
                            IngredienteId = 5,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 7,
                            IngredienteId = 36,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 8,
                            IngredienteId = 37,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 8,
                            IngredienteId = 38,
                            Quantidade = "2 unidade"
                        },
                        new
                        {
                            ReceitaId = 8,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 8,
                            IngredienteId = 29,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 9,
                            IngredienteId = 38,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 9,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 9,
                            IngredienteId = 29,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 41,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 37,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 5,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 36,
                            Quantidade = "2 unidade"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 42,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 10,
                            IngredienteId = 43,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 11,
                            IngredienteId = 37,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 11,
                            IngredienteId = 44,
                            Quantidade = "2 unidade"
                        },
                        new
                        {
                            ReceitaId = 11,
                            IngredienteId = 45,
                            Quantidade = "2 unidade"
                        },
                        new
                        {
                            ReceitaId = 11,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 11,
                            IngredienteId = 29,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 46,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 5,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 40,
                            Quantidade = "2 unidade"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 29,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 12,
                            IngredienteId = 47,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 48,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 37,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 29,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 49,
                            Quantidade = "1 colher"
                        },
                        new
                        {
                            ReceitaId = 13,
                            IngredienteId = 42,
                            Quantidade = "2 unidades"
                        },
                        new
                        {
                            ReceitaId = 14,
                            IngredienteId = 50,
                            Quantidade = "5 unidades"
                        },
                        new
                        {
                            ReceitaId = 15,
                            IngredienteId = 51,
                            Quantidade = "3 unidade"
                        },
                        new
                        {
                            ReceitaId = 15,
                            IngredienteId = 5,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 15,
                            IngredienteId = 42,
                            Quantidade = "1 unidade"
                        },
                        new
                        {
                            ReceitaId = 15,
                            IngredienteId = 3,
                            Quantidade = "a gosto"
                        },
                        new
                        {
                            ReceitaId = 15,
                            IngredienteId = 29,
                            Quantidade = "a gosto"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Receita", b =>
                {
                    b.HasOne("SimplesSaborMVC.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.ReceitaIngrediente", b =>
                {
                    b.HasOne("SimplesSaborMVC.Models.Ingrediente", "Ingrediente")
                        .WithMany("Receitas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplesSaborMVC.Models.Receita", "Receita")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Ingrediente", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("SimplesSaborMVC.Models.Receita", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
